export const types = {
  INIT_START: "init_start",
  INIT_FINISHED: "init_finished",
  CHECK_2ND_DAYS: "check_2nd_days",
  SELECT_NAVI: "select_navi",
  GET_PREDICTIONS_PER_HOURS: "get_predictions_per_hours",
  GET_COUNT_PER_10MIN: "get_count_per_10min",
  GET_COUNT_PER_HOURS: "get_count_per_hours",
  RESIZE_HEATMAP_CONTENT: "resize_heatmap_content",
  RESIZE_TRACKING_HEADER: "resize_tracking_header",
  RESIZE_TRACKING_CONTENT: "resize_tracking_content",
  TRACKING_CHANGE_TEXT: "tracking_change_text",
  TRACKING_CHANGE_SLIDER: "tracking_change_slider",
  TRACKING_SEARCH_START: "tracking_seatch_start",
  TRACKING_SEARCH_FINISHED: "tracking_seatch_finished",
  TRACKING_SELECT_POINT: "tracking_select_point",
  SHOW_DETAIL: "show_detail",
  HIDDEN_DETAIL: "hidden_detail",
  ERROR: "error",
}
