
export const TIME_WINDOW_MINUTES = 60

export const HEATMAP_MAX_INTENSITY = 50
export const HEATMAP_INTENSITY = 1

const MINUTES = 1000 * 60
export const HEATMAP_AUTO_RELOAD_INTERVAL = MINUTES * 10
export const SUMMARY_CHART_AUTO_RELOAD_INTERVAL = MINUTES * 10
export const DETAIL_CHART_AUTO_RELOAD_INTERVAL = MINUTES * 10

export const HEATMAP_ROOM_NUMBER = 4
// todo
// export const HEATMAP_ROOM_NUMBER = 0
